name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv with Python
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
          cache: true

      - name: Sync project dependencies
        run: uv sync --all-groups --frozen

      - name: Run tests
        run: uv run pytest
